# Generated by Django 5.0 on 2024-08-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrcodemodel',
            options={'permissions': [('can_update_qrcode', 'Can update QR code'), ('can_delete_qrcode', 'Can delete QR code')]},
        ),
    ]
